version: '3.3'
services:
    keycloak:
        container_name: keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=h2
        ports:
            - '9990:8080'
        image: 'quay.io/keycloak/keycloak:8.0.2'